### ISSUE TITLE
[Bug] Occasional NPE when selecting "Show Jira Issue" button when no credentials are entered

### ISSUE THREAD

**Issue by jyoo980** [Alison-Li/intelligent-history#35]
Happens occasionally when I press the "Show Jira Issue" button, likely throwing an NPE here:

https://github.com/Alison-Li/intelligent-history/blob/920cf99ed129c18aa1b745bd7fb6b922930d981b/src/main/java/com/alisli/intelligenthistory/services/JiraFetcherService.java#L30

Not the biggest deal, since you'd assume most folks to have actually entered their Jira information before clicking a button, but stranger things have happened.

**Comment by Alison-Li** [comment]
Ahhh, thank you for letting me know @jyoo980! Need to catch all those pesky null pointer exceptions related to the Jira credentials!

**Comment by Alison-Li** [comment]
@jyoo980 By any chance, do you recall the steps taken to reproduce the issue? Is it on first opening a project that the Jira credentials haven't been set for ever before?

**Comment by jyoo980** [comment]
Sorry I should've been more clear, steps to reproduce are:

* Run plugin
* Click "Show Jira Issue" button *without having put your Jira credentials in*
  * You may need to click repeatedly to trigger the NPE, for some reason.

**Comment by Alison-Li** [comment]
Thanks! Didn't take long to reproduce to get the stack trace:
```
java.lang.NullPointerException
	at java.base/java.net.URI$Parser.parse(URI.java:3104)
	at java.base/java.net.URI.<init>(URI.java:600)
	at java.base/java.net.URI.create(URI.java:881)
	at net.rcarz.jiraclient.JiraClient.<init>(JiraClient.java:58)
	at com.alisli.intelligenthistory.services.JiraFetcherService.<init>(JiraFetcherService.java:31)
	at com.alisli.intelligenthistory.actions.ShowJiraMetadataAction.performAction(ShowJiraMetadataAction.java:36)
	at com.alisli.intelligenthistory.actions.ShowJiraMetadataAction.performAction(ShowJiraMetadataAction.java:21)
	at com.intellij.vcs.log.ui.actions.history.FileHistorySingleCommitAction.lambda$actionPerformed$0(FileHistorySingleCommitAction.java:69)
	at com.intellij.vcs.log.data.AbstractDataGetter$loadCommitsData$task$1$run$2.invoke(AbstractDataGetter.kt:64)
	at com.intellij.vcs.log.data.AbstractDataGetter$loadCommitsData$task$1$run$2.invoke(AbstractDataGetter.kt:49)
	at com.intellij.vcs.log.BaseSingleTaskControllerKt$sam$java_lang_Runnable$0.run(BaseSingleTaskController.kt)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```
